/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b57dba4b-b873-4ed1-9960-c296478d5e58 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool gate;
  bool ir1;
  bool ir2;
  bool ir3;
  bool ir4;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <ESP32Servo.h>

#define IR1_PIN 4
#define IR2_PIN 16
#define IR3_PIN 17
#define IR4_PIN 5
#define SERVO_PIN 18
#define GATE_CLOSED_ANGLE 0
#define GATE_OPEN_ANGLE 90
Servo gateServo;
void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();


  // Initialize the IR sensor pins as inputs
  pinMode(IR1_PIN, INPUT);
  pinMode(IR2_PIN, INPUT);
  pinMode(IR3_PIN, INPUT);
  pinMode(IR4_PIN, INPUT);

  // Attach the servo object to its pin
  gateServo.attach(SERVO_PIN);
  
  // Start with the gate open
  gateServo.write(GATE_CLOSED_ANGLE);
  Serial.println("System initialized. Gate is close.");
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  ir1 = !digitalRead(IR1_PIN);
  ir2 = !digitalRead(IR2_PIN);
  ir3 = !digitalRead(IR3_PIN);
  ir4 = !digitalRead(IR4_PIN);

  delay(3000);
}

void onGateChange() {
  // Called when 'gate' variable changes from the dashboard
  if (gate) {
    gateServo.write(GATE_OPEN_ANGLE);
    Serial.println("Gate opened via dashboard");
  } else {
    gateServo.write(GATE_CLOSED_ANGLE);
    Serial.println("Gate closed via dashboard");
  }
}


