// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f5767dbc-37d9-48ca-b161-aaa57377cc95";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGateChange();

bool gate;
bool ir1;
bool ir2;
bool ir3;
bool ir4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gate, READWRITE, ON_CHANGE, onGateChange);
  ArduinoCloud.addProperty(ir1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ir2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ir3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ir4, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
